# Generated by Django 3.1 on 2022-02-04 14:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_productgallary'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productgallary',
            options={'verbose_name': 'productgallery', 'verbose_name_plural': 'product gallery'},
        ),
    ]
