# Generated by Django 3.1 on 2022-01-25 17:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment',
            old_name='mount_paid',
            new_name='amount_paid',
        ),
    ]
